F_frc = 750;
m= 100;
A = [0 0;
    1 0];
B = [1 -F_frc/m;
    0 0];

%% rect test for the robot and load combined 

load ('data.mat');

subs_vars = [ ...
    g, ...
    mp, mt, ...
    m_drv, m_chbt, ...
    h_pivot, h_cmload, h_cmrbt, ...
    l_np1, l_np2, l_nr1, l_nr2, ...
    frc_lr, frc_lf, frc_cstr ...
];

subs_vals = [ ...
    config.env.g, ...
    config.m.pay, config.m.trailer, ...
    config.m.drive, config.m.chbt, ...
    config.h.pivot, config.h.com_load, config.h.com_robot, ...
    config.l.np1, config.l.np2, config.l.nr1, config.l.nr2, ...
    config.frc.load_rear, ...
    config.frc.load_front, ...
    config.frc.rbt_rear ...
];


accel_num = subs(accel_sol, subs_vars, subs_vals);

%% matrix building with the new system 

A_rect = [0 0;
          1 0];
B_rect = [(1/1685) -1.23;
           0 0];

